name: lcov_excluder
description: It is possible to exclude coverage by editing the contents of the lcov.info file.
version: 0.1.0
repository: https://github.com/KyoheiG3/lcov_excluder
documentation: https://github.com/KyoheiG3/lcov_excluder
issue_tracker: https://github.com/KyoheiG3/lcov_excluder/issues

executables:
  lcov_excluder:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  glob: ^2.1.2

dev_dependencies:
  test: ^1.24.9
  flutter_lints: ^3.0.1
